(inline-completion-model) ➜  inline-completion-model git:(main) ✗ prunp pred_def_funcs.py
tokenizer_config.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 26.0/26.0 [00:00<00:00, 181kB/s]
vocab.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.04M/1.04M [00:01<00:00, 651kB/s]
merges.txt: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 456k/456k [00:00<00:00, 947kB/s]
tokenizer.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████| 1.36M/1.36M [00:00<00:00, 2.58MB/s]
config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 665/665 [00:00<00:00, 2.49MB/s]
Traceback (most recent call last):
  File "/home/xlisp/Desktop/inline-completion-model/pred_def_funcs.py", line 157, in <module>
    main()
  File "/home/xlisp/Desktop/inline-completion-model/pred_def_funcs.py", line 149, in main
    train_model(model, train_loader, optimizer, criterion, device)
  File "/home/xlisp/Desktop/inline-completion-model/pred_def_funcs.py", line 108, in train_model
    loss = criterion(outputs.view(-1, outputs.size(-1)), targets.view(-1))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xlisp/anaconda3/envs/inline-completion-model/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xlisp/anaconda3/envs/inline-completion-model/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xlisp/anaconda3/envs/inline-completion-model/lib/python3.11/site-packages/torch/nn/modules/loss.py", line 1293, in forward
    return F.cross_entropy(
           ^^^^^^^^^^^^^^^^
  File "/home/xlisp/anaconda3/envs/inline-completion-model/lib/python3.11/site-packages/torch/nn/functional.py", line 3479, in cross_entropy
    return torch._C._nn.cross_entropy_loss(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 3.06 GiB. GPU 0 has a total capacity of 7.92 GiB of which 2.79 GiB is free. Including non-PyTorch memory, this process has 5.11 GiB memory in use. Of the allocated memory 4.94 GiB is allocated by PyTorch, and 41.99 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
(inline-completion-model) ➜  inline-completion-model git:(main) ✗

